### ISSUE TITLE
Attempt to read property "nilai" on null

### ISSUE THREAD

**Issue by gustom00** [Akbarwp/Laravel-SPK-AHP#1]
pada bagian 
$matriksPenjumlahanPrioritas = DB::table('matriks_penjumlahan_prioritas_utama')->get();
$IR = DB::table('index_random_consistency')->where('ukuran_matriks', $kriteria->count())->first()->nilai;

App \ Http \ Controllers\ DashboardController : 33index

**Comment by Akbarwp** [comment]
Have you run a database seeder? because IR (Index Random Consistency) is the default value for the AHP method, Or you can input manually for the IR,

```
$nilaiIR = [0, 0, 0.58, 1.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51, 1.48, 1.56, 1.57, 1.59];
for ($i = 0; $i < 15; $i++) {
    DB::table('index_random_consistency')->insert([
        "ukuran_matriks" => $i+1,
        "nilai" => $nilaiIR[$i],
        "created_at" => Carbon::now(),
        "updated_at" => Carbon::now(),
    ]);
}
```
You can hide the Alternatif and User seeder,
```
// User::factory()->create([
//   'name' => 'Admin',
//   'email' => 'admin@gmail.com',
//   'password' => Hash::make('Admin123'),
// ]);

// Alternatif::factory(10)->create();
```
